# Generated by Django 3.1.6 on 2021-02-25 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autheticate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
