# Generated by Django 3.1.6 on 2021-03-02 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autheticate', '0003_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('correct', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
